### ISSUE TITLE
no detector, analyzer, indexer on GPU.  

### ISSUE THREAD

**Issue by Tundergit** [AKSHAYUBHAT/DeepVideoAnalytics#104]
# Checklist for submitting an issue 

- Have you verified that docker is installed correctly and e.g. GFW is not preventing downloads?

- Which docker-compose.yml file are you using?

- Please post output of `docker ps -a` or confirm that all containers are running?

- If a specific container is not running or "exited" please post output of `docker logs <name of the container>`

- Is your question about OCR blog post in notebooks/OCR/ ? 

Hello, I cannot get DVA working with GPU support.  Centos 7, updated.  Works in CPU only mode.  Using latest docker-compose-gpu.yml.  qextract working.   q_analyzer, q_indexer, q_detector (any number) not working.  

What version of CUDA, CUDNN do you recommend?

[root@dhcp-10-200-1-80 ~]# nvidia-docker version
NVIDIA Docker: 2.0.1
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:23:40 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:25:03 2017
 OS/Arch:      linux/amd64
 Experimental: false

[root@dhcp-10-200-1-80 ~]# docker ps -a
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                                                    NAMES
85c7bbdca1cf        akshayubhat/dva-auto:gpu   "bash -c 'youtube-..."   About an hour ago   Up 34 minutes       6006/tcp, 0.0.0.0:8888->8888/tcp, 0.0.0.0:8000->80/tcp   dva-server
46468108e814        rabbitmq                   "docker-entrypoint..."   About an hour ago   Up 34 minutes       4369/tcp, 5671-5672/tcp, 25672/tcp                       dva-rmq
fa08dbbdf416        postgres:9.6.6             "docker-entrypoint..."   About an hour ago   Up 34 minutes       5432/tcp                                                 dva-pg

[root@dhcp-10-200-1-80 ~]# nvidia-smi
Tue Dec 19 14:16:39 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.98                 Driver Version: 384.98                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1050    Off  | 00000000:06:00.0  On |                  N/A |
| 39%   25C    P8   ERR! /  65W |    385MiB /  1998MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1687      G   /usr/bin/X                                   265MiB |
|    0      2542      G   /usr/bin/gnome-shell                         117MiB |
+-----------------------------------------------------------------------------+

[root@dhcp-10-200-1-80 ~]# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

**Comment by AKSHAYUBHAT** [comment]
It seems your are using NVIDIA Docker: 2.0.1
The latest version of nvidia-docker requires you change default docker runtime in order to use docker-compose. Please follow instructions here regarding changing default docker runtime.

https://github.com/NVIDIA/nvidia-docker/issues/568 

Also with GTX 1050 you have only 1998 MiB which is not sufficient to run DVA.

**Comment by Tundergit** [comment]
Thanks for the reply!  I did set Nvidia-docker to be the default runtime by adding the line as suggested in the link you sent:  (I had already done this before posting this issue.)  

{
    "runtimes": {
        "nvidia": {
	    "default-runtime": "nvidia",
            "path": "/usr/bin/nvidia-container-runtime",
            "runtimeArgs": []
        }
    }
} 

The largest memory card I currently have access to is a 5GB Quadro P2000, what is the minimum graphics memory required to run DVA?  I suppose that's probably been the problem the whole time.

Thanks again for your very cool work, this is a lot of fun.

**Comment by AKSHAYUBHAT** [comment]
You can try using low-memory compose file. That file runs detectors on GPU while using CPU for other models. You might need to GPU_MEMORY_FRACTION env variable in that compose file.

**Comment by AKSHAYUBHAT** [comment]
https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/deploy/gpu/docker-compose-gpu-low-memory.yml

**Comment by AKSHAYUBHAT** [comment]
Hey the default docker-compose file for GPU's is designed to work with GPU's with at least 12gb of GPU memory, as a result `nvidia-smi` should show that it's maxing out GPU memory and the allocated memory is insufficient. 

Since DVA keeps several networks in memory inception, facenet, text detector, object detector, image tagger fitting all of them on a single GPU is challenging.

**Comment by cxfire16** [comment]
Thanks for the very prompt reply!

Thanks for enlightening me regarding the memory requirement. I would never know that since I'm not encountering any OOM errors at all. I was at once able to load 5 models with my GPU all memory trimmed thru sessions just for the sake of testing, I'm hoping I could do the same. Can you specify minimum hardware requirements? I'm also interested in creating a walkthrough if I get things working. This project is really interesting 👍

**Comment by AKSHAYUBHAT** [comment]
I am in process of updating code to allow you to specify whether a worker should be launched in GPU mode and fraction of GPU memory to allocate (only available with TF) . This is already possible  with multiple GPUs . I will surface it in config.json and use it for single GPU case as well.

**Comment by AKSHAYUBHAT** [comment]
With my latest commit, just run `./dvactl configure` and set number of gpus to 1. 
It will then write a config.json which contains information about allocated memory fraction. 
I have updated default such that only COCO object detector and Text detector runs on GPU. 
with rest running on CPU. 

Also note that you might need latest Nvidia drivers since I think TF version used in the container uses CUDA 8.
