### ISSUE TITLE
SSL errors on Google Cloud

### ISSUE THREAD

**Issue by AKSHAYUBHAT** [AKSHAYUBHAT/DeepVideoAnalytics#106]
Trusty  + Older version of python 2.7 without SNI support is causing SSL errors on first request with GCS inside GKE (when it tries to obtain IAM style auth keys automatically). 

https://github.com/GoogleCloudPlatform/google-auth-library-python/issues/192

Upgrading to Xenial should fix this.

**Comment by AKSHAYUBHAT** [comment]
SSLError: HTTPSConnectionPool(host='www.googleapis.com', port=443): Max retries exceeded with url:<excluded> (Caused by SSLError(SSLError(1, '_ssl.c:1429: error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac'),))

**Comment by AKSHAYUBHAT** [comment]
Fixed by upgrading.

**Comment by ajayakumar123** [comment]
i got same error . can you tell me for upgrading what it resolved

File "/opt/odoo/addons/im_chat/im_chat.py", line 280, in post
    res = requests.post("https://fcm.googleapis.com/fcm/send", data=data, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
SSLError: HTTPSConnectionPool(host='fcm.googleapis.com', port=443): Max retries exceeded with url: /fcm/send (Caused by SSLError(SSLError(1,'_ssl.c:510:error:14090086:SSLroutines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed'),))

**Comment by AKSHAYUBHAT** [comment]
Hey I thought that upgrading to Xenial would fix this issue but it didn't,  apparently there is some race condition in SSL code used in requests. I am currently planning to solve this by making a throwaway requests at container creation and retrying few times with variable timeout since this error appear only on the first request.
