### ISSUE TITLE
Connect to dva-server via LAN

### ISSUE THREAD

**Issue by Tundergit** [AKSHAYUBHAT/DeepVideoAnalytics#118]
Hello, 
I have DVA running locally.  With an older version I was able to connect via another computer on my LAN without any special configuration... but now I see this: 

The docker-compose files use loopback interface (127.0.0.1:8000:80), we recommend forwarding the host OS port (8000)

I have no idea how to do this.  This machine can be slow when processing video - it was easier to access DVA from another computer while this one is busy.

I'm new to this, but super interested, thanks for sharing your work so far!

**Comment by AKSHAYUBHAT** [comment]
You can just edit docker-compose.yml and remove `127.0.0.1:` (from all places it appears) leaving only `8000:80` ,`8888:8888` etc. Otherwise If you are using SSH you can simply add `-L 8000:8000` as an additional argument when you connect. 

The reason for using Loopback interface is to avoid external users from being able to connect to the 8000 port of IP address/machine (e.g. when you deploy on Linode, AWS, GCP etc. ).  But if you are on LAN and with Firewall that filters external traffic you can just remove it.
