### ISSUE TITLE
excute the command “./dvactl start”, occur error （mac os)

### ISSUE THREAD

**Issue by bertonhe** [AKSHAYUBHAT/DeepVideoAnalytics#206]
Recreating webserver ... done
Checking if DVA server is running, waiting for another minute and at most 17 minutes
Checking if DVA server is running, waiting for another minute and at most 16 minutes
Checking if DVA server is running, waiting for another minute and at most 15 minutes
Checking if DVA server is running, waiting for another minute and at most 14 minutes
Checking if DVA server is running, waiting for another minute and at most 13 minutes
Checking if DVA server is running, waiting for another minute and at most 12 minutes
Checking if DVA server is running, waiting for another minute and at most 11 minutes
Checking if DVA server is running, waiting for another minute and at most 10 minutes
Checking if DVA server is running, waiting for another minute and at most 9 minutes
Checking if DVA server is running, waiting for another minute and at most 8 minutes
Checking if DVA server is running, waiting for another minute and at most 7 minutes
Checking if DVA server is running, waiting for another minute and at most 6 minutes
Checking if DVA server is running, waiting for another minute and at most 5 minutes
Checking if DVA server is running, waiting for another minute and at most 4 minutes

Checking if DVA server is running, waiting for another minute and at most 3 minutes
Checking if DVA server is running, waiting for another minute and at most 2 minutes
Checking if DVA server is running, waiting for another minute and at most 1 minutes
Error response from daemon: Container 4dbe4a51f9b532115a41d1c20ad70cf0cdfffda9cbbd61aacd50f80684456306 is not running
Traceback (most recent call last):
  File "./dvactl", line 395, in <module>
    gpu_image=mode_dict['gpu_image'])
  File "/Users/hejubin/DeepVideoAnalytics/deploy/compose/__init__.py", line 198, in handle_compose_operations
    get_auth()
  File "/Users/hejubin/DeepVideoAnalytics/deploy/compose/__init__.py", line 169, in get_auth
    token = subprocess.check_output([DOCKER, "exec", "webserver", "scripts/generate_testing_token.py"]).strip()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['docker', 'exec', 'webserver', 'scripts/generate_testing_token.py']' returned non-zero exit status 1
hejubindeMacBook-Air:DeepVideoAnalytics hejubin$

**Comment by AKSHAYUBHAT** [comment]
1. Can you post output of ‘docker ps -a’?

2. How much memory does your Mac have?

**Comment by AKSHAYUBHAT** [comment]
Closing since no additional information was provided.

**Comment by jackylee1** [comment]
docker ps -a
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                      PORTS                                NAMES
cc27f2bb99bc        akshayubhat/dva-auto:latest   "bash -c 'git reset …"   22 minutes ago      Exited (1) 22 minutes ago                                        webserver
8208c36bdf9e        postgres:9.6.6                "docker-entrypoint.s…"   22 minutes ago      Up 22 minutes               5432/tcp                             dva-pg
7941514e677a        rabbitmq                      "docker-entrypoint.s…"   22 minutes ago      Up 22 minutes               4369/tcp, 5671-5672/tcp, 25672/tcp   dva-rmq
0c76602e8908        bitnami/redis:latest          "/entrypoint.sh /run…"   22 minutes ago      Up 22 minutes               6379/tcp                             dva-redis
efa2b6ddae19        akshayubhat/dva-auto          "/run_jupyter.sh --a…"   44 minutes ago      Exited (0) 25 minutes ago                                        hardcore_montalcini



docker logs webserver
HEAD is now at 0e223cf Merge pull request #211 from AKSHAYUBHAT/master
fatal: unable to access 'https://github.com/akshayubhat/DeepVideoAnalytics/': Could not resolve host: github.com

**Comment by AKSHAYUBHAT** [comment]
fatal: unable to access 'https://github.com/akshayubhat/DeepVideoAnalytics/': Could not resolve host: github.com

this is due to docker not being set up correctly and being unable to access internet.

**Comment by jackylee1** [comment]
192:DeepVideoAnalytics-master anbanglee$ ./dvactl configure
Warning! requests module is required to use exec functionality.
Please select mode { dev, cpu, gpu, kube } >>dev
Please specify path to init process.json or press enter to keep default ( configs/custom_defaults/init_process.json ) >>
Refresh docker images by pulling before start: Y/N , press enter to keep default (Y) >>
Please specify docker CPU image or press enter to keep default ( akshayubhat/dva-auto:latest ) >>
Please specify path to init models.json or press enter to keep default ( configs/custom_defaults/trained_models.json ) >>configs/custom_defaults/trained_models_local.json
/Users/anbanglee/aws.env not found. not passing AWS creds. This is optional and only required if you wish to import/export from AWS S3. To provide credentials please create ~/aws.env with AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY or manually add them to credentials in config.json
/Users/anbanglee/do.env not found. not passing Digital Ocean creds. This is optional and only required if you wish to import/export from Digital Ocean Spaces
Saved config.json
192:DeepVideoAnalytics-master anbanglee$ ./dvactl start
Warning! requests module is required to use exec functionality.
Checking if docker-compose is available
Starting deploy/compose/docker-compose-dev.yaml
Define and run multi-container applications with Docker.

Usage:
  docker-compose [-f <arg>...] [options] [COMMAND] [ARGS...]
  docker-compose -h|--help

Options:
  -f, --file FILE             Specify an alternate compose file
                              (default: docker-compose.yml)
  -p, --project-name NAME     Specify an alternate project name
                              (default: directory name)
  --verbose                   Show more output
  --log-level LEVEL           Set log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  --no-ansi                   Do not print ANSI control characters
  -v, --version               Print version and exit
  -H, --host HOST             Daemon socket to connect to

  --tls                       Use TLS; implied by --tlsverify
  --tlscacert CA_PATH         Trust certs signed only by this CA
  --tlscert CLIENT_CERT_PATH  Path to TLS certificate file
  --tlskey TLS_KEY_PATH       Path to TLS key file
  --tlsverify                 Use TLS and verify the remote
  --skip-hostname-check       Don't check the daemon's hostname against the
                              name specified in the client certificate
  --project-directory PATH    Specify an alternate working directory
                              (default: the path of the Compose file)
  --compatibility             If set, Compose will attempt to convert deploy
                              keys in v3 files to their non-Swarm equivalent

Commands:
  build              Build or rebuild services
  bundle             Generate a Docker bundle from the Compose file
  config             Validate and view the Compose file
  create             Create services
  down               Stop and remove containers, networks, images, and volumes
  events             Receive real time events from containers
  exec               Execute a command in a running container
  help               Get help on a command
  images             List images
  kill               Kill containers
  logs               View output from containers
  pause              Pause services
  port               Print the public port for a port binding
  ps                 List containers
  pull               Pull service images
  push               Push service images
  restart            Restart services
  rm                 Remove stopped containers
  run                Run a one-off command
  scale              Set number of containers for a service
  start              Start services
  stop               Stop services
  top                Display the running processes
  unpause            Unpause services
  up                 Create and start containers
  version            Show the Docker-Compose version information
Pulling/Refreshing container images, first time it might take a while to download the image
latest: Pulling from akshayubhat/dva-auto
Digest: sha256:fcdf8790c146c3df76beaa048e35ab7b2ba6c45bab66e4c5a5020106675becbd
Status: Image is up to date for akshayubhat/dva-auto:latest
Trying to launch containers
docker-compose -f docker-compose-dev.yaml up -d
Checking if DVA server is running, waiting for another minute and at most 20 minutes
Recreating dva-redis ... done
Recreating dva-rmq   ... 
Recreating dva-pg    ... 
Open browser window and go to http://localhost:8000 to access DVA Web UI
Recreating dva-rmq   ... done
Recreating dva-pg    ... done
Recreating webserver ... 

ERROR: for webserver  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)

ERROR: for dva  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
Traceback (most recent call last):
  File "./dvactl", line 397, in <module>
    gpu_image=mode_dict['gpu_image'])
  File "/Users/anbanglee/Downloads/DeepVideoAnalytics-master/deploy/compose/__init__.py", line 198, in handle_compose_operations
    get_auth()
  File "/Users/anbanglee/Downloads/DeepVideoAnalytics-master/deploy/compose/__init__.py", line 169, in get_auth
    token = subprocess.check_output([DOCKER, "exec", "webserver", "scripts/generate_testing_token.py"]).strip()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['docker', 'exec', 'webserver', 'scripts/generate_testing_token.py']' returned non-zero exit status 126



i behind the gfw.and i did as you said ,download the models and put it and do as here
git clone https://github.com/AKSHAYUBHAT/DeepVideoAnalytics
cd DeepVideoAnalytics
./dvactl configure
Please select mode { dev, cpu, gpu, kube } >>cpu
# If gpu option is selected, you can choose number of GPUs
./dvactl start
# Wait few minutes for container images to be downloaded
# You should be able to use both Web UI & jupyter
# To stop containers but retain volumes run
./dvactl stop
# To stop and delete containers and volumes run
./dvactl clean

and  i have configure the local_json  and it show error above

**Comment by AKSHAYUBHAT** [comment]
Thanks I will update reader and add warning message when code runs in CPU mode

**Comment by wlwallis30** [comment]
another question, can I run GPU mode for AMD Radeon GPU?
I doubt it, not sure if dva rely on CUDA where CUDA does not support other kind GPU.
Thanks

**Comment by AKSHAYUBHAT** [comment]
No you cannot use AMD GPU since DVA relies on nvidia-docker
