### ISSUE TITLE
Contributing and licences

### ISSUE THREAD

**Issue by hamstah** [AKSHAYUBHAT/DeepVideoAnalytics#29]
Hi,
I've been playing with the tool and I'd like to make improvements to make it easier to develop

* Simplify docker structure: The current docker-compose/Dockerfile are pretty slow due to the combined server container having everything in it. It makes it slow to start and reload
* Support code reloading: Currently the code is being fetched from github inside the container. We can map it via volumes and have it automatically restarted on change to increase speed of development.
* Improvements to the REST api: The api is pretty bare at the moment and is missing things to allow building of tools with it

I want to make sure I'm not spending time making changes which aren't going to be accepted upstream, so I wanted your opinion on the ideas.

Also, I can't contribute these changes back to the project with a restrictive licence, would you be open to changing the project to the MIT or similarly permissive licence (The dva code only, not the datasets if that's an issue).

Thanks

**Comment by AKSHAYUBHAT** [comment]
Hi  thanks for your interest,

1. I am actively refactoring the Dockerfile structure by splitting it into a base (OS/Apt dependancies) + repo/python-requirements. However I want to keep entire code in one repo/container, right now the model weights which are heavy are kept in the container but in future would be moved to media folder/volume to reduce duplication and size of container. 

2. For development its not too difficult to simply install the stack (in a virtualenv) on to the native MacOS or Ubuntu. This is actually what I do on my on MacBookPro. Like I mentioned in parent comment keeping weights inside the volume should provide significant speedup. 

3. The REST API is bare since I am actively developing the underlying data model. E.g. I still have not completely ruled out merging of Annotations & Detections into a single model, or having provenance TaskEvent field for annotations / detections to keep track of origin. 

Currently the repo is going through significant often breaking changes, however around first week of June I plan on freezing the data model and adopt a proper versioning system with versioned API. 

I also completely understand your concerns regarding the choice of Open Source license, while building DVA, I have tried my best to ensure that all code used is either MIT/BSD/Apache, to allow permissive release. Even then there are some repositories which either lack a license (Code released by researchers)  or have non standard license (Creative Commons CC-BY-NC 4.0 used by FAISS). I will also make a decision regarding final licensing of the code (BSD/MIT/Apache vs AGPL vs etc.) by early june concurrent with adoption of versioning.

**Comment by hamstah** [comment]
Thanks for the quick response.
I'll wait until it's stable and for the new licence before investing time working on it.

**Comment by samuel-davis** [comment]
I also would like to contribute to the codebase, is there any update on the licensing change ?

**Comment by AKSHAYUBHAT** [comment]
Sorry for the delay, it's taking longer than expected to get an agreement from all stakeholders. Should have an answer soon.

**Comment by paulxiong** [comment]
there is an error when I run docker-compose up: 
ERROR:  relation "dvaapp_deletedvideo" already exists
how can I fix it?

**Comment by AKSHAYUBHAT** [comment]
@paulxiong the recent commit erased migrations. You can either delete existing data in volumes using `docker-compose down -v` or  manually migrate the database.

**Comment by paulxiong** [comment]
@AKSHAYUBHAT  works after used docker-compose down -v

**Comment by paulxiong** [comment]
here is another issue when I try to use search:
dva-server | Internal Server Error: /Search
dva-server | Traceback (most recent call last):
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
dva-server |     response = get_response(request)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
dva-server |     response = self.process_exception_by_middleware(e, request)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
dva-server |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
dva-server |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
dva-server |     return view_func(request, *args, **kwargs)
dva-server |   File "/root/DVA/dvaapp/views.py", line 398, in search
dva-server |     qp.wait()
dva-server |   File "/root/DVA/dvaapp/operations/query_processing.py", line 301, in wait
dva-server |     raise ValueError(e)
dva-server | ValueError: The operation timed out.

**Comment by AKSHAYUBHAT** [comment]
@paulxiong fixed but please use a separate issue for future bugs.
