### ISSUE TITLE
image search error

### ISSUE THREAD

**Issue by Aspirinkb** [AKSHAYUBHAT/DeepVideoAnalytics#31]
I add one image on the dashboard, upload a .zip images file, select facenet indexer, start 'approximate search' or 'exact search', then a error come out as follows:
<img width="1273" alt="2017-05-03 10 24 14" src="https://cloud.githubusercontent.com/assets/5260197/25646898/861b2d74-2fef-11e7-8bab-32067a7ad3f0.png">

**Comment by AKSHAYUBHAT** [comment]
This is because it takes a while for the zip file to be processed. You can view the status of incomplete and successful tasks in the tasks page from sidebar. Once the images in zip files are indexed. It will show corresponding index entries, and then when you search it will return a result. 

The system also shows various logs on /status page if the error persists  page contents from /status
