### ISSUE TITLE
docker_GPU, sudo docker-compose up, produce error

### ISSUE THREAD

**Issue by northeastsquare** [AKSHAYUBHAT/DeepVideoAnalytics#5]
Hello, thank you for your great project! after I install docker and other dependence, then
pip install --upgrade nvidia-docker-compose
git clone https://github.com/AKSHAYUBHAT/DeepVideoAnalytics && cd DeepVideoAnalytics/docker_GPU && nvidia-docker-compose up 

produce errors as follows, and I change fabfile.py , but result no difference. 
def start_server_container_gpu(perform_test=False):
    """
    Start sever container using nginx and uwsgi
    :param test:
    :return:
    """
    local('sleep 60')
    migrate()
    local('chmod 0777 -R /tmp')
    **local("mv configs/nginx.conf /etc/nginx/")
    local("mv configs/nginx-app.conf /etc/nginx/sites-available/default")
    local("mv configs/supervisor-app.conf /etc/supervisor/conf.d/")**
    local("python manage.py collectstatic --no-input")
    local("chmod 0777 -R dva/staticfiles/")
    local("chmod 0777 -R dva/media/")
    launch_queues(True)
    if perform_test:
        test()
    local('supervisord -n')

My system is Ubuntu 14.04, GPU titan x. Could give me some advice? I got stuck with it for two days.

dva-server4 | I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
dva-server4 | libdc1394 error: Failed to initialize libdc1394
dva-server4 | Operations to perform:
dva-server4 |   Apply all migrations: admin, auth, contenttypes, djcelery, dvaapp, sessions
dva-server4 | Running migrations:
dva-server4 |   No migrations to apply.
dva-server4 | mv: cannot stat 'docker_GPU/configs/nginx.conf': No such file or directory
dva-server4 | 
dva-server4 | Fatal error: local() encountered an error (return code 1) while executing 'mv docker_GPU/configs/nginx.conf /etc/nginx/'
dva-server4 | 
dva-server4 | Aborting.
dva-server4 | [localhost] local: sleep 60
dva-server4 | [localhost] local: python manage.py makemigrations
dva-server4 | [localhost] local: python manage.py migrate
dva-server4 | [localhost] local: chmod 0777 -R /tmp
dva-server4 | [localhost] local: mv docker_GPU/configs/nginx.conf /etc/nginx/
dva-server4 exited with code 1

**Comment by AKSHAYUBHAT** [comment]
The instruction did not mention running `./rebuild.sh` to build the latest version of the image
I have updated the instructions, you need to run `./rebuild.sh` so that it recreates the docker image with latest version of the repo.

`cd deepvideoanalytics && git pull && cd docker_GPU && ./rebuild.sh && nvidia-docker-compose up `

> mv: cannot stat 'docker_GPU/configs/nginx.conf': No such file or directory

Means that the git repo inside the container is not at the latest version, since it cannot find nginx.conf .  

Additionally if you still have the container running you can manually go inside it by running `./shell.sh`, and then execute by a `git pull && fab start_server_container_gpu:1`
