### ISSUE TITLE
two bugs

### ISSUE THREAD

**Issue by nanqiangyipo** [AKSHAYUBHAT/DeepVideoAnalytics#70]
1. The class VideoList in dvaapp/views.py should add a method 'get_queryset' to exclude query items. Otherwise , the pagination will be not correct on videos webpage if amount of the query items larger than page size .
my codes：
```   
def get_queryset(self):
      return Video.objects.filter(query=False)
```

2. If I upload one file with a Chinese name, decode error appears on the task status webpage. I call the encode method with 'utf-8' argument when add the header attribute into context.
my codes in get_context_data method：
   ` context['header'] = "video/dataset : {}".format(context['video'].name.encode('utf-8'))`

**Comment by AKSHAYUBHAT** [comment]
Hi @nanqiangyipo 

Regarding 1, since introduction of DVAPQL Process / Task, each query is NOT treated as a separate video with single image. as a result that field is no longer required or paginating on it is no longer required. . 

Regarding 2, I plan to add proper internationalization + UTF support by either updated strings or switching to 3.0 which would be required anyway in near future (2 ~ 3 years). I will check if there is any solution that can be applied across django in consistent manner until then. One option is to use __unicode__() everywhere in models.py. 

https://docs.djangoproject.com/en/1.11/ref/unicode/
