### ISSUE TITLE
CUDA out of memory messages

### ISSUE THREAD

**Issue by gpp8p** [AKSHAYUBHAT/DeepVideoAnalytics#71]
The application appears to be fully functional, but I did see this towards the end of the startup:

dva-server | 2017-09-02 01:12:24.695358: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
dva-server | 2017-09-02 01:12:24.695368: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
dva-server | 2017-09-02 01:12:24.695385: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
dva-server | 2017-09-02 01:12:24.695387: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
dva-server | 2017-09-02 01:12:24.695388: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
dva-server | 2017-09-02 01:12:24.771692: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
dva-server | 2017-09-02 01:12:24.771919: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties: 
dva-server | name: GeForce GTX 1060 3GB
dva-server | major: 6 minor: 1 memoryClockRate (GHz) 1.835
dva-server | pciBusID 0000:01:00.0
dva-server | Total memory: 2.94GiB
dva-server | Free memory: 253.19MiB
dva-server | 2017-09-02 01:12:24.771931: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 
dva-server | 2017-09-02 01:12:24.771935: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y 
dva-server | 2017-09-02 01:12:24.771940: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1060 3GB, pci bus id: 0000:01:00.0)
dva-server | 2017-09-02 01:12:24.772471: E tensorflow/stream_executor/cuda/cuda_driver.cc:924] failed to allocate 451.88M (473835008 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
dva-server | 2017-09-02 01:12:24.772760: E tensorflow/stream_executor/cuda/cuda_driver.cc:924] failed to allocate 406.70M (426451712 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
dva-server | 2017-09-02 01:12:24.773078: E tensorflow/stream_executor/cuda/cuda_driver.cc:924] failed to allocate 366.03M (383806720 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
dva-server | 2017-09-02 01:12:24.773384: E tensorflow/stream_executor/cuda/cuda_driver.cc:924] failed to allocate 329.42M (345426176 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
dva-server | 2017-09-02 01:12:24.773649: E tensorflow/stream_executor/cuda/cuda_driver.cc:924] failed to allocate 296.48M (310883584 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
dva-server | 2017-09-02 01:12:24.773915: E tensorflow/stream_executor/cuda/cuda_driver.cc:924] failed to allocate 266.83M (279795456 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY

-George PIpkin
Afton, Virginia

**Comment by AKSHAYUBHAT** [comment]
CUDA out of memory errors are common unless you have GPU with > 11 GB RAM.

Deep Video Analytics default processing pipeline requires storing 4 models (Facenet, Inception, Mobilenet, MTCNN ) in memory and allocating GPU memory for each of them. As a result, while you can control GPU memory allocation by adding a special environment variable for each model that tells Tensorflow how much GPU memory to allocates.  For four models its near limit of most commodity gaming GPUs. The solution is to use multiple GPU and allocate workers processing models to different GPUs. Or unload / reset the session. However resetting the session leads to higher latency since it will take few seconds to a minute for TensorFlow to reload the model.  

Another approach is to use a single session which loads multiple models as disjoint subgraphs. 
And run only worker that consumes from all queues. I have tried this in past but without any success. There are several issue with this approach such as it does not allows you to dynamically load a new model, Celery 4.0.2 has some open bugs when workers consume from multiple queues at the same time, etc.
