### ISSUE TITLE
While docker pulling on MAC OS getting following error

### ISSUE THREAD

**Issue by kumarneeraj2005** [AKSHAYUBHAT/DeepVideoAnalytics#9]
ERROR: Service 'dva' failed to build: The command '/bin/sh -c pip install https://s3.amazonaws.com/pytorch/whl/cu75/torch-0.1.9.post2-cp27-none-linux_x86_64.whl' returned a non-zero code: 137

Please help me out how to resolve this issue

**Comment by AKSHAYUBHAT** [comment]
Hi, 
The issue is likely due to not enough memory available to your Docker instance. You can try to increase memory available to Docker and build the latest image in the repo or simply use `docker pull akshayubhat/dva:cpu` though it will pull an older version of the image. 

From https://github.com/docker/compose/issues/1554
> For anyone encountering this, it appears to be a race condition when running out of memory on the host.

**Comment by kumarneeraj2005** [comment]
Thanks a lot! its working now,, i really appreciate for your super quick reply 🥇
