### ISSUE TITLE
run DeepVideoAnalytics project problem

### ISSUE THREAD

**Issue by doudoubean** [AKSHAYUBHAT/DeepVideoAnalytics#91]
![1512113875 1](https://user-images.githubusercontent.com/7455568/33472605-fe4e8f42-d6ad-11e7-962f-cb5d27858c8d.jpg)
when i delete old docker images about DeepVideoAnalytics and run DeepVideoAnalytics project again, this problem occurs. It is shown as above. I operate this according to the official link, this is shown as followings:
pip install --upgrade nvidia-docker-compose
git clone https://github.com/AKSHAYUBHAT/DeepVideoAnalytics
cd DeepVideoAnalytics/deploy/single
nvidia-docker-compose -f docker-compose-gpu.yml up

**Comment by AKSHAYUBHAT** [comment]
This happened because the migration was run again, since the tables changed, and it lead to creation of multiple copies of models. If you are not storing any data in docker volumes from previous runs. just run 
`nvidia-docker-compose -f docker-compose-gpu.yml down -v` to remove those volumes followed by 
`nvidia-docker-compose -f docker-compose-gpu.yml up` to start again.
