### ISSUE TITLE
Benchmark CTPN + CRNN

### ISSUE THREAD

**Issue by pribadihcr** [AKSHAYUBHAT/DeepVideoAnalytics#92]
Dear @AKSHAYUBHAT,

Have you compare the performance CTPN(caffe version)+CRNN(pytoch version) with CTPN+CRNN (tensorflow version). Look like the CTPN+CRNN caffe/pytorch is better than tensorflow.

Thanks

**Comment by AKSHAYUBHAT** [comment]
Thank for bringing this to my attention, I am aware of the relatively poorer performance with respect to Caffe implementation. However this implementation is capable of producing oriented bounding boxes which I plan to enable soon and retrain. Which should improve the performance. 

Also if GPL license is not an issue I would highly recommend using EAST instead of CTPN.
You can find dockerized version of EAST here https://github.com/akshayubhat/EAST
