### ISSUE TITLE
Database files are incompatible with server

### ISSUE THREAD

**Issue by ericjenott** [AKSHAYUBHAT/DeepVideoAnalytics#96]
Hello Mr. Bhat,

After pulling the latest docker images, I get the following error when starting the containers using "nvidia-docker-compose -f docker-compose-gpu.yml up" in the deploy/single directory.  It seems that postgres has been upgraded to 10.1 but the database has not been migrated.  I've tried everything I can think of to fix this over the last two days, but nothing has worked so far.

dva-pg    | 2017-12-07 03:03:27.665 UTC [1] FATAL:  database files are incompatible with server
dva-pg    | 2017-12-07 03:03:27.665 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 9.6, which is not compatible with this version 10.1.
dva-pg exited with code 1

**Comment by AKSHAYUBHAT** [comment]
Hi you can take following steps to ensure that code / containers do not change.

1. Remove 'git pull' from the command section in docker-compose-gpu.yml this ensure that the DVA code does not updates by pulling from github.

2. Also in docker-compose-gpu.yml replace `image: postgres` with exact postgres version image: postgres:9.6.6` as found on https://hub.docker.com/_/postgres/ It appears that 10.1 was pushed with "latest" tag, since it pull latest by default it appears that led to an error. Further you can remove the local "latest" postgres image and pull old one by running `docker rmi postgres && docker pull postgres:9.6.6`
