### ISSUE TITLE
Un-dockerized version  

### ISSUE THREAD

**Issue by abhi-kumar** [AKSHAYUBHAT/DeepVideoAnalytics#97]
Is there a way to run the whole module locally without a docker?

**Comment by AKSHAYUBHAT** [comment]
Yes, manually install all dependencies in requirements.txt, PyTorch, Tensor Flow, MxNET as specified in the Dockerfile. Edit settings.py [1] to reflect the username, host and password for RabbitMQ and Postgres. Add other environment variables to select models/workers you intend to run. [2] If you do not have Postgres and RabbitMQ installed you can just run those two via Docker using this compose file, and connect to them from DVA running on the host OS. [3]
Launch workers by running `fab launch` which adds environment variables. 

It's surely possible, since that's how I develop on a Mac, but its not a good way to run/use it, since Dockerfiles / docker-compose files are self documenting in both requirements/dependencies and configurations. I will hopefully have more instructions on developing locally soon. 

[1] https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/dva/settings.py

[2] https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/blob/master/fabfile.py#L355

[3] https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/tree/master/deploy/dev

**Comment by AKSHAYUBHAT** [comment]
With new directory structure you can now simply mount host server directory. 
This lets you use your host IDE etc. while changes are run inside the container. 

https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/tree/master/deploy/dev
